version: '3.3'
services:

  db:
    image: postgres:13.0-alpine
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    restart: always
    networks:
      - foodgram_network

  backend:
    image: borya2072/foodgram-backend:latest
    restart: always
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
      - redoc:/app/api/docs/
    env_file:
      - ./.env
    depends_on:
      - db
    networks:
      - foodgram_network

  frontend:
    image: borya2072/foodgram-frontend:latest
    volumes:
      - ../frontend/:/app/result_build/
    networks:
      - foodgram_network

  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ../docs/redoc.html:/usr/share/nginx/html/api/docs/redoc.html
      - static_value:/var/html/static/
      - media_value:/var/html/media/
      - ../frontend/build:/usr/share/nginx/html/
    restart: always
    depends_on:
      - backend
    networks:
      - foodgram_network

volumes:
  static_value:
  media_value:
  postgres_data:
  redoc:

networks:
  foodgram_network: