# Generated by Django 3.2.18 on 2023-03-20 20:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='subscribe',
            name='unique_subscription',
        ),
        migrations.RenameField(
            model_name='subscribe',
            old_name='subscriber',
            new_name='user',
        ),
        migrations.AddField(
            model_name='subscribe',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscribing', to=settings.AUTH_USER_MODEL, verbose_name='Автор, на которого подписываются'),
        ),
        migrations.AlterUniqueTogether(
            name='subscribe',
            unique_together={('user', 'author')},
        ),
        migrations.AddConstraint(
            model_name='subscribe',
            constraint=models.UniqueConstraint(fields=('user', 'author'), name='unique_subscription'),
        ),
        migrations.RemoveField(
            model_name='subscribe',
            name='author_sub',
        ),
    ]
